<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-BG9IMGR" name="test.order.CheapComputerBuyingTest" tests="4" failures="1" timestamp="2022-03-09T14:42:00 ICT" time="11.035" errors="0">
  <testcase name="testCheapCompBuying" time="1.363" classname="test.order.CheapComputerBuyingTest"/>
  <system-out/>
  <testcase name="testCheapCompBuying" time="1.411" classname="test.order.CheapComputerBuyingTest"/>
  <system-out/>
  <testcase name="testCheapCompBuying" time="8.252" classname="test.order.CheapComputerBuyingTest"/>
  <system-out/>
  <testcase name="testSomething" time="0.009" classname="test.order.CheapComputerBuyingTest">
    <failure type="java.lang.AssertionError" message="Failed by....sth">
      <![CDATA[java.lang.AssertionError: Failed by....sth
at org.testng.Assert.fail(Assert.java:110)
at test.order.CheapComputerBuyingTest.testSomething(CheapComputerBuyingTest.java:33)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:32)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:467)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:750)
]]>
    </failure>
  </testcase> <!-- testSomething -->
  <system-out/>
</testsuite> <!-- test.order.CheapComputerBuyingTest -->
